name: Backend CD

on:
  push:
    branches:
      - main
    paths:
      - "starter/backend/**"
  workflow_dispatch:

env:
  AWS_REGION: us-east-1

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install pipenv
        run: pip install pipenv

      - name: Install dependencies
        working-directory: starter/backend
        run: pipenv install --dev

      - name: Lint
        working-directory: starter/backend
        run: pipenv run lint

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install pipenv
        run: pip install pipenv

      - name: Install dependencies
        working-directory: starter/backend
        run: pipenv install --dev

      - name: Test
        working-directory: starter/backend
        run: pipenv run test

  build:
    name: Build and Push
    needs:
      - lint
      - test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.ASIA4AJRFIDMX536YB4G}}
          aws-secret-access-key: ${{ secrets.P/kysjEvBpw9d/ibFS/s2TBtEjJNZMhkw+FPA3A0}}
          aws-session-token: ${{ secrets.IQoJb3JpZ2luX2VjEA0aCXVzLXdlc3QtMiJGMEQCIBat82MvfG3uwLGlZ9oXWPVtbCN6GBEMWqxZO/uQmq2aAiBmfaoOKVOI5CkQqSeHhSnOz4A8te4rmwUU5SZTA5dCJirHAgjW//////////8BEAMaDDgyNTI3MzY5NjQ3MyIMbQWng416OVjHR8geKpsCUfQzYhELCSs/udd0IdpiPMX2/dklBo/5flR6zFFDbfL4tnhqAR7bSfifmoIq4OzhyGvhryVzr2kYCLPqPnH0QLJb0rlIRBDVPfc0naZ7cl9TBAEy/XtRgUvTR50CWvJnYcRwhZNurbJzLwwMgX7IwpRn2x4q5QslK56165NT884UkHg+ceD7pv1In8VfzHIc8har6n9QQEQ1OFdILFuz4ca2IFmA23yEkpPDYdfU4fVkiLjaFPA7+cP3Ieb3EkbJJAPL6GAuqkorgBWIeIchlkIjeH1DQzaVe+WEUXRPU2eWSRslDOeUdg4AzKdnuHAvxGbLOzxpyJJYwFD/lnyRZjgCZ8NW8+jkbOQ6tlNPakuw+xL52teCmus0BDC07ePUBjqeAXY2Vre7cKjH9gYir54X4YIxj/viRfZN4XvS3oNDPwdg7XatX+7MGuGYx0t4UnQd+E5lG9OdB7shAmtuug0659ZMKnFaQSU+XMLZ1fGTB5vC5Ffsc5YRKPfP69WmzZ2KQBAplXsV5p5Ct2rHKH1rad8Quj7bzpa5olniDexgdNALaED7MuOF8mjqzHjqaMmgoz1wiAE44mML2eWAxIfi}}
          aws-region: ${{ env.us-east-1}}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: mp-backend
          IMAGE_TAG: ${{ github.sha }}
        working-directory: starter/backend
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.ASIA4AJRFIDMX536YB4G}}
          aws-secret-access-key: ${{ secrets.P/kysjEvBpw9d/ibFS/s2TBtEjJNZMhkw+FPA3A0}}
          aws-session-token: ${{ secrets.IQoJb3JpZ2luX2VjEA0aCXVzLXdlc3QtMiJGMEQCIBat82MvfG3uwLGlZ9oXWPVtbCN6GBEMWqxZO/uQmq2aAiBmfaoOKVOI5CkQqSeHhSnOz4A8te4rmwUU5SZTA5dCJirHAgjW//////////8BEAMaDDgyNTI3MzY5NjQ3MyIMbQWng416OVjHR8geKpsCUfQzYhELCSs/udd0IdpiPMX2/dklBo/5flR6zFFDbfL4tnhqAR7bSfifmoIq4OzhyGvhryVzr2kYCLPqPnH0QLJb0rlIRBDVPfc0naZ7cl9TBAEy/XtRgUvTR50CWvJnYcRwhZNurbJzLwwMgX7IwpRn2x4q5QslK56165NT884UkHg+ceD7pv1In8VfzHIc8har6n9QQEQ1OFdILFuz4ca2IFmA23yEkpPDYdfU4fVkiLjaFPA7+cP3Ieb3EkbJJAPL6GAuqkorgBWIeIchlkIjeH1DQzaVe+WEUXRPU2eWSRslDOeUdg4AzKdnuHAvxGbLOzxpyJJYwFD/lnyRZjgCZ8NW8+jkbOQ6tlNPakuw+xL52teCmus0BDC07ePUBjqeAXY2Vre7cKjH9gYir54X4YIxj/viRfZN4XvS3oNDPwdg7XatX+7MGuGYx0t4UnQd+E5lG9OdB7shAmtuug0659ZMKnFaQSU+XMLZ1fGTB5vC5Ffsc5YRKPfP69WmzZ2KQBAplXsV5p5Ct2rHKH1rad8Quj7bzpa5olniDexgdNALaED7MuOF8mjqzHjqaMmgoz1wiAE44mML2eWAxIfi}}
          aws-region: ${{ env.us-east-1}}

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
            --region $AWS_REGION \
            --name udacity

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Deploy backend
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: mp-backend
          IMAGE_TAG: ${{ github.sha }}
        working-directory: starter/backend/k8s
        run: |
          kustomize edit set image backend=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          kustomize build | kubectl apply -f -